# Usar a imagem base Node.js
FROM node:16-alpine

# Diretório de trabalho no container
WORKDIR /usr/src/app

# Copiar arquivos do projeto
COPY package.json .
COPY index.js .
COPY .env .

# Instalar dependências
RUN npm install

# Expor a porta da aplicação
EXPOSE 3000

# Comando padrão
CMD ["node", "index.js"]
